#Init zabbix web-server service
---
- name: "{{ service_name }} service config on host"
  template:
    src: systemd/zabbix-web.service.j2
    dest: "/etc/systemd/system/{{ service_name }}.service"
    backup: yes
  notify: "{{ service_name }} restart"
